In [2]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [6]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.ensemble import RandomForestRegressor

In [9]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[50,100]} 



grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

In [10]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   
# print classification report 
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8745520289325067

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.182198,0.004445,0.010603,0.000490,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",0.801814,0.749373,0.834226,0.804937,0.764584,0.790987,0.030365,14
1,0.373801,0.015523,0.022799,0.002041,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.804383,0.749687,0.830822,0.802041,0.767069,0.790801,0.028865,15
2,0.149000,0.009653,0.010800,0.000748,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.811273,0.761376,0.824121,0.827606,0.758851,0.796645,0.030331,11
3,0.278000,0.013638,0.023601,0.003720,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.812639,0.768440,0.833238,0.835120,0.756582,0.801204,0.032777,6
4,0.138200,0.006765,0.012001,0.000632,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.799290,0.766108,0.835644,0.822003,0.761191,0.796847,0.029530,10
5,0.312598,0.031708,0.024602,0.002578,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.810640,0.778057,0.833506,0.831785,0.763611,0.803520,0.028249,1
6,0.204798,0.022167,0.011601,0.000490,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.799754,0.753608,0.837618,0.795270,0.758461,0.788942,0.030672,16
7,0.404800,0.018800,0.023201,0.003187,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.801863,0.754976,0.833133,0.811603,0.763556,0.793026,0.029489,13
8,0.153599,0.012225,0.012201,0.001469,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.805773,0.770527,0.829271,0.823586,0.759176,0.797667,0.028123,9
9,0.294200,0.017382,0.022400,0.001356,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.810516,0.773113,0.838969,0.824757,0.759596,0.801390,0.030291,5
10,0.164000,0.011576,0.012800,0.000748,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.801452,0.771117,0.837673,0.829263,0.753579,0.798617,0.032426,8
11,0.293597,0.018193,0.020401,0.001498,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.816695,0.770640,0.836929,0.829284,0.757512,0.802212,0.032071,4
12,1.018994,0.019951,0.011402,0.001497,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",0.779057,0.757738,0.819031,0.801388,0.759673,0.783377,0.023805,18
13,2.009017,0.062034,0.020200,0.001167,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.777116,0.774215,0.816104,0.804390,0.756629,0.785691,0.021561,17
14,0.617000,0.018354,0.012198,0.002227,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.788588,0.774477,0.830543,0.821204,0.755865,0.794135,0.028071,12
15,1.262527,0.041602,0.021599,0.002334,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.808272,0.777632,0.840108,0.824764,0.766144,0.803384,0.027856,2
16,0.638516,0.010365,0.011004,0.001096,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.800972,0.768231,0.840759,0.839805,0.761378,0.802229,0.033831,3
17,1.289927,0.012629,0.022997,0.002449,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.804666,0.773760,0.834144,0.822286,0.761532,0.799278,0.027749,7
18,0.321708,0.015720,0.010999,0.000890,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",0.741545,0.709352,0.798507,0.782101,0.745380,0.755377,0.031572,21
19,0.626921,0.026629,0.021004,0.002190,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.750820,0.727682,0.806497,0.788950,0.746279,0.764046,0.029104,19
20,0.207601,0.009092,0.011801,0.001471,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.757072,0.702513,0.814552,0.796644,0.692914,0.752739,0.048722,24
21,0.410805,0.011669,0.022200,0.001327,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.756086,0.713648,0.818970,0.784460,0.703026,0.755238,0.043295,22
22,0.214201,0.010666,0.012001,0.001265,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.753478,0.701664,0.815657,0.790368,0.712719,0.754777,0.043737,23
23,0.349402,0.022063,0.016999,0.001415,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.761102,0.701426,0.820383,0.797687,0.699650,0.756050,0.049117,20

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:26
BMI:26
Children:3
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[47699.6144301]