In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [5]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [8]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[50,100]} 



grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

In [9]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   
# print classification report 
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8723143393285292

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.178402,0.010708,0.011401,0.000489,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",0.804806,0.750938,0.838621,0.796423,0.769077,0.791973,0.030228,13
1,0.358004,0.025588,0.020398,0.001022,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.808709,0.748946,0.828256,0.801257,0.764515,0.790337,0.029239,15
2,0.148001,0.012744,0.010799,0.000401,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.803414,0.770604,0.840631,0.826193,0.763792,0.800927,0.030065,4
3,0.265001,0.013265,0.020200,0.000401,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.810138,0.770127,0.838955,0.835072,0.761104,0.803079,0.032274,1
4,0.132002,0.007590,0.014000,0.005100,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.806272,0.760070,0.833371,0.828823,0.762596,0.798226,0.031501,10
5,0.273799,0.010476,0.021200,0.001471,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.803180,0.767534,0.835813,0.832213,0.756941,0.799136,0.032357,8
6,0.174999,0.011188,0.012201,0.002481,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.802760,0.747213,0.828499,0.801000,0.760736,0.788042,0.029779,17
7,0.334798,0.017198,0.020002,0.000634,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.799758,0.753058,0.835466,0.803808,0.762154,0.790849,0.029965,14
8,0.138000,0.005441,0.011799,0.001719,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.801773,0.772775,0.830209,0.822572,0.757271,0.796920,0.028088,11
9,0.276800,0.019198,0.020999,0.001414,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.802085,0.774249,0.838247,0.829516,0.757456,0.800311,0.031019,6
10,0.145001,0.014070,0.012400,0.002498,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.796966,0.765590,0.834276,0.822724,0.757856,0.795482,0.030194,12
11,0.273399,0.027347,0.019202,0.001167,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.809567,0.769392,0.829275,0.833796,0.761881,0.800782,0.029925,5
12,0.968798,0.032007,0.009000,0.000004,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",0.779709,0.766709,0.823075,0.815948,0.760260,0.789140,0.025676,16
13,1.937197,0.045625,0.019001,0.001096,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.783333,0.764904,0.815588,0.805675,0.763102,0.786520,0.021155,18
14,0.579996,0.018677,0.010202,0.000979,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.800051,0.782894,0.834594,0.827917,0.759270,0.800945,0.028011,3
15,1.165600,0.029371,0.018999,0.002530,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.804088,0.772645,0.836957,0.831354,0.761674,0.801343,0.030245,2
16,0.572399,0.013733,0.009401,0.000491,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.803904,0.763601,0.842344,0.820609,0.763144,0.798720,0.031331,9
17,1.165800,0.026590,0.018999,0.001673,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.804178,0.775028,0.838435,0.820844,0.761902,0.800077,0.028299,7
18,0.292198,0.006460,0.010400,0.000489,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",0.736287,0.725495,0.812199,0.777888,0.747437,0.759861,0.031481,21
19,0.580200,0.026362,0.020200,0.001167,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.752261,0.734745,0.805355,0.785192,0.750220,0.765555,0.025810,19
20,0.178799,0.007304,0.010400,0.001021,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.754658,0.713018,0.811305,0.784196,0.693151,0.751266,0.043683,24
21,0.367199,0.014522,0.017400,0.002576,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.768353,0.711493,0.823540,0.796727,0.707650,0.761553,0.045907,20
22,0.185999,0.006694,0.011600,0.001200,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.748924,0.706616,0.807616,0.797072,0.699979,0.752041,0.044497,23
23,0.285196,0.029930,0.012001,0.002100,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.758540,0.708852,0.819692,0.793549,0.692119,0.754550,0.048510,22

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

In [ ]:
#The R_score value for best parameter 
#{'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8723143393285292