In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [5]:
from sklearn.ensemble import RandomForestRegressor

In [6]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[50,100]} 



grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
#grid.fit(X_train, y_train)
grid.fit(indep, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

In [7]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 50}:

In [8]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.250800,0.011268,0.015800,0.001167,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",0.844521,0.770325,0.857268,0.821073,0.834237,0.825485,0.030038,15
1,0.503599,0.022912,0.026602,0.001019,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.851258,0.768456,0.857223,0.818629,0.836110,0.826335,0.031875,14
2,0.178800,0.007441,0.022999,0.010098,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.858618,0.782875,0.851681,0.826928,0.837533,0.831527,0.026700,9
3,0.378598,0.053063,0.029202,0.003601,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859162,0.778820,0.857024,0.826175,0.840639,0.832364,0.029326,5
4,0.180399,0.012499,0.020800,0.005844,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.857120,0.772272,0.857307,0.826952,0.838700,0.830470,0.031297,10
5,0.350797,0.009766,0.028802,0.003600,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.858339,0.779999,0.864693,0.826663,0.843363,0.834612,0.030299,2
6,0.255399,0.014332,0.018801,0.003763,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.844672,0.760098,0.856461,0.813123,0.833522,0.821575,0.033894,16
7,0.490201,0.035453,0.028826,0.003863,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.852102,0.771924,0.854728,0.819531,0.836583,0.826974,0.030265,13
8,0.188400,0.010090,0.015599,0.000491,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.853179,0.772568,0.858792,0.822599,0.838354,0.829098,0.030936,12
9,0.364399,0.014949,0.027201,0.000980,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859198,0.777330,0.859322,0.830352,0.831863,0.831613,0.029923,8
10,0.199202,0.029459,0.015798,0.000750,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.858774,0.777205,0.863672,0.828473,0.845431,0.834711,0.031236,1
11,0.349770,0.031075,0.026399,0.001358,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858595,0.777056,0.853087,0.826708,0.844304,0.831950,0.029497,6
12,1.758197,0.232861,0.015603,0.001498,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",0.830585,0.766226,0.845249,0.816566,0.836283,0.818982,0.027975,18
13,3.686323,0.268274,0.032000,0.007511,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.837443,0.765561,0.847617,0.822020,0.834295,0.821387,0.029084,17
14,1.159399,0.124660,0.016201,0.001165,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.856493,0.777509,0.849647,0.828420,0.847301,0.831874,0.028731,7
15,2.092124,0.056277,0.030398,0.005712,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.860680,0.780808,0.856234,0.824501,0.844757,0.833396,0.029120,3
16,1.277009,0.217967,0.021003,0.008945,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.854029,0.781980,0.846879,0.823617,0.840907,0.829482,0.025794,11
17,2.699800,0.162269,0.042600,0.023027,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.854328,0.782104,0.857595,0.828628,0.841632,0.832857,0.027363,4
18,0.546198,0.025981,0.015402,0.001355,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",0.820896,0.746601,0.823439,0.819747,0.802214,0.802579,0.028980,20
19,1.090198,0.104865,0.036800,0.012737,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.821240,0.753029,0.822293,0.829674,0.797720,0.804791,0.028019,19
20,0.333397,0.041171,0.016801,0.001937,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.814367,0.722446,0.817791,0.788597,0.770139,0.782668,0.034806,24
21,0.577999,0.071893,0.032601,0.003498,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.808727,0.727491,0.819370,0.791930,0.782787,0.786061,0.031934,22
22,0.350200,0.026071,0.016801,0.001469,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.809397,0.727618,0.828876,0.790873,0.777254,0.786803,0.034326,21
23,0.513197,0.037574,0.024201,0.002925,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.807241,0.726907,0.820875,0.788704,0.780095,0.784765,0.032230,23

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

In [9]:
#0.8347